[build]
  command = "npm install && npm run build"
  commandOrigin = "config"
  publish = "/opt/build/repo/dist"
  publishOrigin = "config"
  [build.environment]
    VITE_API_BASE_URL = "https://dermodel-backend-c1b9c7f69d88.herokuapp.com/api"
    NODE_VERSION = "20"
    NODE_ENV = "production"

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 5173
  framework = "vite"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  origin = "config"